aws

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,68 +1,50 @@
-#!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
+#!/bin/bash
+# Author: Noah Yoshida
+# 
+# This check to see if you are commiting anything with a private key, or any
+# tokens. It will abort the commit if there was something bad found.
 # Note: exit with non-zero exit code to abort the commit
-echo "derp"
-FORBIDDEN=( PRIVATE-KEY )
 
-for i in "${FORBIDDEN[@]}"
+# Constants --------------------------------------------------
+THIS_FILE=$(echo $0 | rev | cut -d /  -f 1 | rev)
+COMMIT_FILES=$(git diff --cached --name-only)
+
+# Cannot have space-seperated strings, replacing with '-'
+declare -a FORBIDDEN_TERMS=("PRIVATE-KEY" 
+                            "aws_secret_key_id"
+                            "aws_access_key_id")
+# ------------------------------------------------------------
+
+set_exit_cond () {
+  if [ $1 -eq 0 ] && [ $2 != $THIS_FILE ] # Ignores this file!
+  then
+    EXIT_COND=1
+    echo -e $3
+    return 1
+  fi
+  return 0 
+}
+
+# Constants -------------------------------------------------------------
+EXIT_COND=0
+
+for i in $COMMIT_FILES;
 do
-  echo(`git diff --cached --name-only`)
-  exit 0
-  # | grep ".js" |xargs sed 's/ //g'|grep "ha_mobile.debug=true" && \
+  cat $i | grep "ssh" | grep "alias" &> /dev/null
+  set_exit_cond $? $i "Exposing IP address to external machine in:\n\t$i"
 
-        #echo 'COMMIT REJECTED Found ha_mobile.debug=true references. Please remove them before commiting' && exit 1
+  for BAD_STRING in "${FORBIDDEN_TERMS[@]}"; 
+  do
+    # I want to replace '-' with a space, to get the accurate string 
+    UPDATED_STRING=$(echo $BAD_STRING | sed 's/-/ /g')
 
-  git diff --cached --name-only | \
-        grep -E $FILES_PATTERN | \
-        GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $i && \
-        echo 'COMMIT REJECTED Found'  $i 'references. Please remove them before commiting' && exit 1
+    cat $i | grep "$UPDATED_STRING" &> /dev/null
+    set_exit_cond $? $i "Found $UPDATED_STRING in file:\n\t$i" 
+  done
 done
 
-exit 0
+[ $EXIT_COND -eq 1 ] && echo "Found something bad, aborting commit..."
 
-# if git rev-parse --verify HEAD >/dev/null 2>&1
-# then
-# 	against=HEAD
-# else
-# 	# Initial commit: diff against an empty tree object
-# 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-# fi
+# exit based on whether there were violating files or not
+exit $EXIT_COND 
 
-# # If you want to allow non-ASCII filenames set this variable to true.
-# allownonascii=$(git config --bool hooks.allownonascii)
-
-# # Redirect output to stderr.
-# exec 1>&2
-
-# # Cross platform projects tend to avoid non-ASCII filenames; prevent
-# # them from being added to the repository. We exploit the fact that the
-# # printable range starts at the space character and ends with tilde.
-# if [ "$allownonascii" != "true" ] &&
-# 	# Note that the use of brackets around a tr range is ok here, (it's
-# 	# even required, for portability to Solaris 10's /usr/bin/tr), since
-# 	# the square bracket bytes happen to fall in the designated range.
-# 	test $(git diff --cached --name-only --diff-filter=A -z $against |
-# 	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-# then
-# 	cat <<\EOF
-# Error: Attempt to add a non-ASCII file name.
-
-# This can cause problems if you want to work with people on other platforms.
-
-# To be portable it is advisable to rename the file.
-
-# If you know what you are doing you can disable this check using:
-
-#   git config hooks.allownonascii true
-# EOF
-# 	exit 1
-# fi
-
-# # If there are whitespace errors, print the offending file names and fail.
-# exec git diff-index --check --cached $against --
